import "../globals.css";
import Loader from "@/components/Loader"
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs"

export const metadata = {
    title:'next.js',
    description: 'Generated by next.js'
}
export default function RootLayout({children}){
    return(
        <ClerkProvider>
        <html lang = 'em'>
        <body>
        <ClerkLoading>
        <Loader />
        </ClerkLoading>
            <ClerkLoaded>{children}</ClerkLoaded>
        </body>
        </html>
        </ClerkProvider>
    )
}